/*メモ帳が終了するまで待つサンプル
*/
debuginfo 1;

#dll=loaddll(currentmacrodirectory+"\\..\\hm_process\\bin\\Release\\x64\\hm_process.dll");
#handle=dllfuncw(#dll,"Spawn","notepad","");
#success=dllfuncw(#dll,"Start",#handle);

#counter=0;
#exit=0;
while(#exit==0){
	#exit=dllfuncw(#dll,"WaitForExitWithTimeOut",#handle,1000);

	/*ここで独自の処理（バックグランドタスク）を動かすことが出来ます。
	*/
	debuginfo"#counter="+str(#counter);
	#counter = #counter + 1;
}

freedll(#dll);
debuginfo"Finish";